# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lake',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
