# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160317_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='slug',
            field=models.SlugField(default=1, help_text='A label for URL config.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
