# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lake_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
